### ISSUE TITLE
Azure, EC2, and GCE plugins do not use FQDN ansible module names. [Patch available]

### ISSUE THREAD

**Issue by beargiles** [ansible-community/molecule-plugins#119]
Azure, EC2, and GCE plugins do not use FQDN ansible module names.

**Comment by beargiles** [comment]
I've tried to create a pull request for this but it doesn't appear in the list above. The command I used was

     git request-pull main https://github.com/beargiles/molecule-plugins use-fqdn

**Comment by apatard** [comment]
I'm not sure that git request-pull should be working with github. You can use github web interface (and possibly the gh cli)

**Comment by apatard** [comment]
btw, I think that PR #105 should have fixed the azure part of this (future) PR. So, you'll have to rebase first
