### ISSUE TITLE
Add ansible-lint for cookiecutter in CI jobs

### ISSUE THREAD

**Issue by zhan9san** [ansible-community/molecule-plugins#122]
Related to #119

Currently, the cookiecutter directory is excluded in ansible-lint configuration.

It may need to run 'molecule init -d xxx' to generate the playbook from cookiecutter.

The lint issue in Azure plugin has been fix in #105

**Comment by apatard** [comment]
sounds a good idea but are you sure that it'll work ? iirc ansible-lint was not really happy with cookiecutter templates

**Comment by apatard** [comment]
oh, right... Got confused with previous line, I thought you wanted to remove the corresponding exclude_path line in ansible-lint configuration
