### ISSUE TITLE
Update community.docker collection for fix issue with request lib.

### ISSUE THREAD

**Issue by ngnix** [ansible-community/molecule-plugins#160]
Please update community.docker collection for fix request lib issue, see original [MR](https://github.com/ansible-collections/community.docker/issues/611)

**Comment by konstruktoid** [comment]
isnt this comment correct? https://github.com/ansible-collections/community.docker/issues/611#issuecomment-1536763593

**Comment by zhan9san** [comment]
Would you mind creating a PR to fix this issue?
