### ISSUE TITLE
podman containers break on Get passwd entries for USER env

### ISSUE THREAD

**Issue by lod** [ansible-community/molecule-plugins#181]
Release v23.5.0 includes the commit https://github.com/ansible-community/molecule-plugins/commit/b5509a19465ba39cfedff0e6450524620a2d6d2f

This causes the following error

```
Molecule default > destroy 00:01
PLAY [Destroy] *****************************************************************
TASK [Get passwd entries for USER env] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "One or more supplied key could not be found in the database."}
```

I believe the root of this is that the USER variable is not set.

**Comment by grcancelliere** [comment]
@lod can you describe your environment? I'll change that part to get the user home even if `$USER` is  not set

**Comment by grcancelliere** [comment]
@lod sorry for breaking your workflow, the PR I'm currently writing uses `whoami` instead of `$USER`, is it available in your environment?

**Comment by lod** [comment]
Thanks for looking at this @grcancelliere,  Sorry I didn't respond promptly

`whoami` will work fantastically


My environment is a gitlab runner executing a basic Debian container.

```
# env
HOSTNAME=a8d732721bfc
PWD=/
container=podman
HOME=/root
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```
