### ISSUE TITLE
EC2 public_ip_address not always set after ec2_instance creation

### ISSUE THREAD

**Issue by kuwv** [ansible-community/molecule-plugins#43]
*Overview*

While creating EC2 instances with the default create playbook the "Collect instance configs" task will fail randomly. This is due to the ec2_instance (set with assign_public_ip) being created but not waiting to be populated with the public IP address. The register attribute is then undefined when that above task is run.

```
ansible            6.1.0
ansible-compat     2.2.0
ansible-core       2.13.2
molecule           3.5.1
molecule-ec2       0.3
```

I attempted downgrading from molecule 0.4.* to 0.3.5. with corresponding downgrade for molecule-ec2 also. It did not work.

This issue is obviously with ec2_instance itself but since it directly effects molecule-ec2 I submitted this issue for tracking purposes. Also, this could potentially be resolved with different designs without directly modify ec2_instance.

**Comment by danielpodwysocki** [comment]
Ran into this recently - is anyone working on a patch for the default cookiecutter? In case nobody's got the bandwidth, I'd be happy to make an MR for this as well.

**Comment by kuwv** [comment]
@danielpodwysocki sure that would be great. I've been waiting for some free time to do it but just haven't had time.

**Comment by danielpodwysocki** [comment]
@kuwv Awesome - I bumped an MR here. https://github.com/ansible-community/molecule-plugins/pull/70
