### ISSUE TITLE
Configuring exposed ports

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible-community/molecule-plugins#77]
Is there any configuration that allows for the tuning of exposed ports? I'm looking to try to run a container image that contains my API and then allows molecule to test my roles out to see if the expected actions/outputs are completed.

**Comment by bbaassssiiee** [comment]
Here is an example:
https://github.com/ansiblebook/ansible_role_ssh/blob/main/molecule/default/molecule.yml
