### ISSUE TITLE
Docker: Unable to set platform of docker container

### ISSUE THREAD

**Issue by dankow** [ansible-community/molecule-plugins#94]
The docker plugin does not support the `platform` parameter of [community.docker.docker_container](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module). This means that we cannot tell `molecule` to create e.g. a `linux/arm64` container on a `arm64` system.

**Comment by Maddog2050** [comment]
I'm experiencing a similar issue on my M1 MacBook, where a container that only has an amd64 image causes molecule to fail as it tries to download the arm version of the container which doesn't exist. A workaround that I found was to pull the image for the platform that you want before running molecule.

I made the exact changes as in your PR #95 and was just about to submit it as a PR and then I found this issue and these changes negate the need for the workaround.

**Comment by apatard** [comment]
The PR 95 has been merged so I guess that this PR may be closed.
