### ISSUE TITLE
Remove molecule filters

### ISSUE THREAD

**Issue by grumpy-penguin** [ansible-community/molecule-plugins#96]
The Azure plugin continues to include the molecule filters that were removed in 2020, previous efforts on other plugins was completed with [Ansible community issue 2872](https://github.com/ansible-community/molecule/issues/2872).

**Comment by apatard** [comment]
hm. right. that's quite annoying. I'm wondering why it has been added here if it has been broken for ages (and nobody cared to fix it). I can make a PR next week, but I'm wondering if it really worths it.

**Comment by grumpy-penguin** [comment]
I've rasied [PR98](https://github.com/ansible-community/molecule-plugins/pull/98). 

Possibly not really worth it - its a bit of a stop gap for me right now to use this plugin. 

I think in the long term for this plugin to be really useful to me, it needs to support Windows instances too, much like the GCP plugin does. But I think thats a long term tactical use case, I'd much rather be in a position where I can use ACI or AKS to test roles against both Windows and Linux platforms with containers.

**Comment by apatard** [comment]
Ok, thanks. We'll see what @ssbarnea thinks of that. We can fix the playbooks too but if there's nobody at least testing the plugin from time to time, it's doomed to happen again.

**Comment by apatard** [comment]
As mentioned in the PR, looks like it's fixed now, so closing this issue.
